config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root "posts#index"
  resources :posts do
    resources :comments, only:[:create, :destroy]
    resources :likes, only: [:create, :destroy]
  end
  resources :contacts, only: [:create]
  get 'about', to: 'pages#about', as: 'about'
  get 'contact', to: 'pages#contact', as: 'contact'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user

  validates :description, presence: true
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable

  has_many :posts
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post

  def create
    @comment = Comment.new(comment_params)
   
    respond_to do |format|
      if @comment.save
        # CommentMailer.with(post: @post).send.deliver_now
        format.html { redirect_to @post, notice: "Comment successfully created", status: :created }
        format.js 
      else
        format.html { redirect_to @post, notice: "Something went wrong" }
        format.js
        @errors = @comment.errors.full_messages
      end
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    if @comment.destroy
      respond_to do |format|
        format.html { redirect_to @post, notice: "Was deleted with success" }
        format.js
      end
    else
      respond_to do |format|
        format.html { redirect_to @post, notice: "Something went wrong." }
        format.js
      end
    end
  end
  

  private

  def set_post
    @post = Post.find(params[:post_id])
  end
  def comment_params
    params.require(:comment).permit(:description, :post_id, :user_id)
  end
  
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  
  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      respond_to do |format|
        format.html { redirect_to root_path, notice:  "Contact sent successfully" }
        format.js
      end
    else
      respond_to do |format|
        format.html { redirect_to root_path, notice:  "Error registering contact" }
        format.js
      end
    end
  end

  private

  def contact_params
    params.require(:contact).permit(:name, :email)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_post

  def create
    @like = Like.new(post_id: @post.id, user_id: current_user.id)
    respond_to do |format|
      if @like.save
        format.html { redirect_to @post, notice: "like successfully created", status: :created }
        format.js
      else
        format.html { redirect_to @post, notice: "Something went wrong" }
        format.js
        @errors = @like.errors.full_messages
      end
    end
  end

  def destroy
    @like = Like.find(params[:id])
    if @like.destroy
      respond_to do |format|
        format.html { redirect_to @post, notice: "Was deleted with success" }
        format.js
      end
    else
      respond_to do |format|
        format.html { redirect_to @post, notice: "Something went wrong." }
        format.js
      end
    end
  end
  

  private

  def set_post
    @post = Post.find(params[:post_id])
  end

  def like_params
    params.require(:like).permit(:post_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only:[:new]
  before_action :set_post, only:[:show, :edit, :update, :destroy]

  def index
    @posts = Post.includes(:comments).order("created_at DESC")
  end

  def new
    @post = Post.new
  end
  

  def show
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      respond_to do |format|
        format.html { redirect_to @post, notice: "Created with success." }
        format.js
      end
    else
      respond_to do |format|
        format.html { redirect_to @post, notice: "Something went wrong." }
        format.js
      end
    end
  end
  
  def edit
  end

  def update
      if @post.update(post_params)
        respond_to do |format|
          format.html { redirect_to @post, notice: "Updated with success." }
          format.js
        end
      else
        respond_to do |format|
          format.html { redirect_to @post, notice: "Something went wrong." }
          format.js
        end
      end
  end
  
  def destroy
    if @post.destroy
      respond_to do |format|
        format.html { redirect_to @post, notice: "Deleted with success." }
        format.js
      end
    else
      respond_to do |format|
        format.html { redirect_to @post, notice: "Something went wrong." }
        format.js
      end
    end
  end

  private
  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :content, :user_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def css_class_btn(action_name)
    action_name == 'new' ? 'is-primary' : 'is-success'
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
  def liked?(post_id)
    Like.exists?(post_id: post_id, user_id: current_user.id)
  end

  def like_id(post_id)
    like = Like.find_by(post_id: post_id, user_id: current_user.id)
    like.id
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<div class="column is-full" id="comment_<%= comment.id %>">
  <p><b><%= comment.user.email %>:</b> <%= comment.description %></p>
  <% if user_signed_in? %>
    <% if comment.user.id == current_user.id %>
    <%= link_to t('page.links.delete', model: comment.model_name), post_comment_path(@post, comment), 
                                                      method: :delete,
                                                      class: 'button is-warning is-rounded is-small delete_comment', 
                                                      data: {remote: true} %>
  <% end %>  
  <% end %>
   
</div>

app/views/comments/create.js.erb
$(document).ready(function(){
  $('#comment_form').on('ajax:success', function(e){
    <% if !@comment.errors.any? %>
      $("#comments").html("<%= j render @post.comments %>");
      $('#comment_description').prop('value','');
      $('#comments_count').html('<%= "#{t("page.title.comments")} #{@post.comments.count}" %>');
      $(".label").html("Description").removeClass('has-text-danger');

      Toastify({
        text: I18n.t('messages.success.create',{model: "Comentário"}),
        position: "center",
        gravity: "top",
        backgroundColor: "linear-gradient(to right, #00b09b, #96c93d)",
      }).showToast();
      
      $('.delete_comment').text(I18n.t('page.links.delete', {model: "Comentário"}));
    <% else %>
      $(".label").html("<%= j @errors[0] %>").addClass('has-text-danger');
    <% end %>
  }); 
   
  $('#comment_form').on('ajax:error', function(e){
    Toastify({
      text: I18n.t('messages.error.create',{model: "Comentário"}),
      position: "center",
      gravity: "top",
      backgroundColor: "linear-gradient(to right, #00b09b, #96c93d)",
    }).showToast();
  });

  
});

app/views/comments/destroy.js.erb
$(document).ready(function(){
  $('.delete_comment').on('ajax:success', function(e){
    
    $('#comments_count').text('<%= "#{t("page.title.comments")} #{@post.comments.count}" %>');

    $("#comment_<%= params[:id] %>").remove();

     Toastify({
        text: I18n.t('messages.success.destroy', {model: "Comentário"}),
        position: "center",
        gravity: "top",
        backgroundColor: "linear-gradient(to right, #00b09b, #96c93d)",
      }).showToast();
      $('.delete_comment').text(I18n.t('page.links.delete', {model: "Comentário"}));
  });

  $('.delete_comment').on('ajax:error', function(){
     Toastify({
        text: I18n.t('messages.error.destroy', {model: "Comentário"}),
        position: "center",
        gravity: "top",
        backgroundColor: "linear-gradient(to right, #00b09b, #96c93d)",
      }).showToast();
  });
});

app/views/contacts/create.js.erb
$(document).ready(function(){
  $("form[data-remote='true']").on('ajax:success', function(e){
    $('#contact_name').prop('value', '');
    $('#contact_email').prop('value', '');

    Toastify({
        text: "Contact sent with success.",
        position: "center",
        gravity: "top",
        backgroundColor: "linear-gradient(to right, #00b09b, #96c93d)",
      }).showToast();
  });

  $("form[data-remote='true']").on('ajax:error', function(e){
    Toastify({
        text: "Something went wrong.",
        position: "center",
        gravity: "top",
        backgroundColor: "linear-gradient(to right, #ff0079, #ff00ac)",
      }).showToast();
  });
})

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DemoBlog</title>
    <%= csrf_meta_tags %>
    <script type="text/javascript" src = "../../assets/froala_editor.pkgd.min.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render 'shared/menu' %>

    <div class="app">
      <% flash.each do |type, msg| %>
      <section class="section">
        <div id="messages" class="box mt-3 mx-3 py-3 px-3  <%= !type.eql?('error') ? "has-background-success has-text-white" : "has-background-danger has-text-white" %>">
          <p><%= msg %></p>
        </div>
      </section>
      <% end %>

      <%= yield %>
    </div>

    <%= render 'shared/footer' %>

  </body>
</html>

app/views/likes/create.js.erb
$(document).ready(function() {
  $("a.like[data-remote='true']").on('ajax:success', function(e){
    e.preventDefault();
    e.stopPropagation();
    $(e.currentTarget).hide();
    $(e.target).parent().prepend("<%= j link_to 'DisLike', post_like_path(@post,like_id(@post.id)), method: :delete, remote: true, class: 'button is-danger dislike is-rounded mt-3' if liked?(@post.id) %>");
    $(e.target).parent().children('.dislike').html('<i class="fa fa-thumbs-down"></i>');
    $(e.target).parent().children('.likes').html("<%= j 'Likes '.concat(@post.likes.count.to_s) %>")
    $(e.currentTarget).remove();
  });
});

app/views/likes/destroy.js.erb
$(document).ready(function() {
  $("a.dislike[data-remote='true']").on('ajax:success', function(e){
    e.preventDefault();
    e.stopPropagation();
    $(e.currentTarget).hide();
    $(e.target).parent().prepend("<%= j link_to 'Like', post_likes_path(@post), method: :post, remote: true, class: 'button is-danger like is-rounded mt-3' unless liked?(@post.id) %>");
    $(e.target).parent().children('.like').html('<i class="fa fa-thumbs-up"></i>');
    $(e.target).parent().children('.likes').html("<%= j 'Likes '.concat(@post.likes.count.to_s) %>")
    $(e.currentTarget).remove();
  });
});

app/views/pages/_about.html.erb
<%= content_for :page_title, t('page.title.about')  %>

<section class="section">
  <div class="container is-small">
    <h2 class="title">
      <%= t('page.title.about') %>
    </h2>
    <h3 class="subtitle">
      <%= t('page.subtitle.about') %>
    </h3>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt, quam et libero iste cupiditate doloribus veniam nisi harum consectetur, fugit repellendus dicta hic! Possimus quia voluptas consequatur sint totam tempora.</p>
    
  </div>
</section>

app/views/pages/_contact.html.erb
<%= content_for :page_title, "Contact" %>

<section class="section">
  <div class="container">
    <h2 class="title">
      <%= t('page.title.contact') %>
    </h2>
    <h3 class="subtitle">
      <%= t('page.subtitle.contact') %>
    </h3>
    
    <div class="content">
      <%= form_with model: Contact.new do |form| %>
        <div class="field">
          <%= form.label :name, class: 'label' %>
          <div class="control">
            <%= form.text_field :name, class:'input', placeholder: 'Name' %>
          </div>
        </div>
        
        <div class="field">
          <%= form.label :email, class: 'label' %>
          <div class="control">
            <%= form.email_field :email, class:'input', placeholder: 'Email' %>
          </div>
        </div>
        
        <div class="control">
          <%= form.submit nil, class: "button #{css_class_btn(action_name)} mt-3 is-rounded"%>
        </div>
            
      <% end %>
    </div>
    
  </div>
</section>

app/views/pages/about.html.erb
<%= content_for :page_title, "About" %>

<section class="section">
  <div class="container">
    <h2 class="title">
      About
    </h2>
    <h3 class="subtitle">
      blog demo
    </h3>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt, quam et libero iste cupiditate doloribus veniam nisi harum consectetur, fugit repellendus dicta hic! Possimus quia voluptas consequatur sint totam tempora.</p>
    
  </div>
</section>

app/views/pages/about.js.erb
$(document).ready(function(){
    $('#about_page').on("ajax:success", function(){
        $('#root_page').text('<%= t("page.title.about") %>');
        $('#home_page').removeClass('is-warning');
        $('#contact_page').removeClass('is-warning');
        $('#about_page').addClass('is-warning');
        $('#messages').remove();
        $('.app').html("<%= j render 'about' %>");
    });
    
});

app/views/pages/contact.html.erb
<%= content_for :page_title, "Contact" %>

<section class="section">
  <div class="container">
    <h2 class="title">
      Contact
    </h2>
    <h3 class="subtitle">
      see plus
    </h3>
    
    <div class="content">
      <%= form_with model: Contact.new, local: true do |form| %>
        <div class="field">
          <%= form.label :name, class: 'label' %>
          <div class="control">
            <%= form.text_field :name, class:'input', placeholder: 'Name' %>
          </div>
        </div>
        
        <div class="field">
          <%= form.label :email, class: 'label' %>
          <div class="control">
            <%= form.email_field :email, class:'input', placeholder: 'Email' %>
          </div>
        </div>
        
        <div class="control">
          <%= form.submit nil, class: "button #{css_class_btn(action_name)} mt-3 is-rounded" %>
        </div>
            
      <% end %>
    </div>
    
  </div>
</section>

app/views/pages/contact.js.erb
$(document).ready(function(){
    $('#contact_page').on("ajax:success", function (e, data, status, xhr){
        $('#root_page').text('<%= t("page.title.contact") %>');
        $('#home_page').removeClass('is-warning');
        $('#about_page').removeClass('is-warning');
        $('#contact_page').addClass('is-warning');
        $('#messages').remove();
        $('.app').html("<%= j render 'contact' %>");
    })
})

app/views/posts/_comment_form.html.erb
<%= form_with model: [post, post.comments.build], id: 'comment_form' do |form|%>
          <div class="field">
            <%= form.label :description, class:'label' %>
            <div class="control">
              <%= form.text_area :description, class:'textarea' %>
            </div>
          </div>

          <div class="field">
            <div class="control">
              <%= form.hidden_field :post_id, class:'input' %>
            </div>
          </div>

          <div class="control">
            <%= form.hidden_field :user_id, value: current_user.id %>
          </div>

          <div class="control">
            <%= form.submit nil, class: 'button is-primary is-rounded' %>
          </div>
        <% end %>

app/views/posts/_edit.html.erb
<%= content_for :page_title, t('page.title.edit', model: @post.title) %>

<section class="section">
  <div class="container">
    <h2 class="title">
      <%= t('page.title.edit', model: @post.model_name) %>      
    </h2>
    <%= render 'form', post: @post %>    
  </div>
</section>

app/views/posts/_form.html.erb
<%= form_with model: post do |form| %>
  <div class="field">
    <%= form.label :title, class: 'label' %>
    <div class="control">
      <%= form.text_field :title, class:'input', placeholder: 'Title' %>
    </div>
  </div>
  
  <div class="field">
    <%= form.label :content, class: 'label' %>
    <div class="control">
      <%= form.text_area :content, id: 'editor', class:'textarea', placeholder: 'Content ...' %>
    </div>
  </div>
  <div class="field">
    <div class="control">
      <%= form.hidden_field :user_id, value: current_user.id %>
    </div>
  </div>
   
  <div class="control">
    <%= link_to t('page.links.comeback'), posts_path, id: 'back_page', remote: true, class: "button is-danger is-rounded mt-3" %>
    <%= form.submit nil, class: "button #{css_class_btn(action_name)} mt-3 is-rounded" %>
  </div>
      
<% end %>

app/views/posts/_index.html.erb
<%= content_for :page_title, t('page.title.index') %>

<%= render @posts %>

<% unless @posts.present? %>
  <section class="container is-larger mb-3">
    <div class="box">
      <h1 class="title">Não há nenhum post no momento</h1>
      <p>
        <%= link_to 'Criar post', new_post_path, data: {remote: true, type: :json}, class: 'button is-primary is-rounded new_post' if user_signed_in? %>
      </p>
    </div>
  </section>
<% end %>

app/views/posts/_new.html.erb
<%= content_for :page_title, t('page.title.new', model: @post.model_name) %>

<section class="section">
  <div class="container">
    <h2 class="title">
      <%= t('page.title.new', model: @post.model_name) %>
    </h2>
    <%= render 'form', post: @post %>    
  </div>
</section>

app/views/posts/_post.html.erb
<section class="container is-larger mb-3" id="post_<%= post.id%>">
  <div class="box">
    <h1 class="title">
      <%= link_to post.title, post, remote: true, class: 'show_post' %>
    </h1>
    <h5>
      <%= t('page.subtitle.autor',autor: post.user.email) %>
    </h5>    
    <p><%= post.content.html_safe %></p>
      <div class="container like_content">

      <% if user_signed_in? %>
        <%= link_to post_likes_path(post), method: :post, remote: true, class: "button is-danger like is-rounded mt-3" do %>
          <i class="fa fa-thumbs-up"></i>
        <% end unless liked?(post.id) %>

        <%= link_to post_like_path(post,like_id(post.id)), method: :delete, remote: true, class: "button is-danger dislike is-rounded mt-3" do %>
          <i class="fa fa-thumbs-down"></i>
        <% end if liked?(post.id) %>

        <% if current_user.id === post.user_id %>
          <%= link_to edit_post_path(post), remote: true, class: 'button is-success is-rounded edit_post mt-3' do %>
            <i class="fa fa-pencil"></i>
          <% end %>

          <%= link_to post, method: :delete, class: 'button is-danger is-rounded delete_post mt-3', data:{confirm: "Tem certeza?", remote: true} do %>
            <i class="fa fa-trash"></i>
          <% end %>
        <% end %>
          <span class="button is-info is-rounded m-3">
            <i class="fa fa-comments"></i>
            <b class="m-2"><%= "#{post.comments.count}" %></b>
          </span>    
          <span class="button is-secondary is-rounded mt-3 likes"><%= "Likes #{post.likes.count}" %></span>
        </div>
      <% end %>
      <span class="mt-5"><%= t('page.subtitle.created',time: time_ago_in_words(post.created_at)) %></span>    
  </div>
</section>

app/views/posts/_show.html.erb
<%= content_for :page_title, @post.title %>

<section class="section">
  <div class="container">
    <div class="columns">
      <div class="column">
        <h1 class="title">
          <%= @post.title %>
          <%= link_to t('page.links.comeback'), posts_path, id: 'back_page', remote: true, class: "button is-danger is-rounded mt-3 is-pulled-right" %>
        </h1>
        <h2 class="subtitle">
          <%= t('page.subtitle.autor',autor: @post.user.email) %>
        </h2>        
        <div class="box">
          <p>
            <span class="mb-3"><%= t('page.subtitle.created',time: time_ago_in_words(@post.created_at)) %></span>
            <hr/>
            <%= @post.content.html_safe %>
          </p>
        </div>
        
      </div>
    </div>
    <div class="column">
      <div class="box">
        <h3 class="subtitle" id="comments_count"><%= "#{t('page.title.comments')} #{@post.comments.count}" %></h3>
        <div class="container">
          <div class="columns is-multiline" id="comments">
            <%= render @post.comments %>
          </div>
        </div>
      </div>
    </div>
    <div class="column">
      <h2 class="subtitle"><%= t('page.title.add_comment') %></h2>
      <div class="box" id="box_comment">
        <%= render 'comment_form', post: @post if user_signed_in? %>
        <%= link_to t('page.links.login_to_comment'), new_user_session_path, class: 'button is-primary is-rounded' unless user_signed_in? %>
      </div>
  </div>
</section>

app/views/posts/create.js.erb
$(document).ready(function(){
  $("form[data-remote='true']").on('ajax:success', function(){
    $('.app').html("<%= j render 'show', post: @post %>");
    Toastify({
      text: I18n.t('messages.success.create',{model: "<%= @post.model_name %>"}),
      position: "center",
      gravity: "top",
      backgroundColor: "linear-gradient(to right, #00b09b, #96c93d)"
    }).showToast();
  });

  $("form[data-remote='true']").on('ajax:error', function(){
    Toastify({
      text: I18n.t('messages.error.create',{model: "<%= @post.model_name %>"}),
      position: "center",
      gravity: "top",
      backgroundColor: "linear-gradient(to right, #ff000b, #ff002f)"
    }).showToast();
  });
});

app/views/posts/destroy.js.erb
$(document).ready(function(){
  $('.delete_post').on('ajax:success', function(){
    $('#post_<%= params[:id] %>').remove();
    Toastify({
      text: I18n.t('messages.success.destroy',{model: "<%= Post.model_name %>"}),
      position: "center",
      gravity: "top",
      backgroundColor: "linear-gradient(to right, #ff0000, #32ff00)"
    }).showToast();
  });

  $('.delete_post').on('ajax:error', function(){
    Toastify({
      text: I18n.t('messages.error.destroy',{model: "<%= Post.model_name %>"}),
      position: "center",
      gravity: "top",
      backgroundColor: "linear-gradient(to right, #ff0099, #ff0000)"
    }).showToast();
  });
})

app/views/posts/edit.js.erb
$(document).ready(function(){
  $('.edit_post').on('ajax:success', function(){
    $('#messages').remove();
    $('#root_page').text('<%= t("page.title.edit", model: @post.model_name) %>');
    $('.app').html("<%= j render 'edit' %>");

    new FroalaEditor('#editor',{
      language: 'pt_pt'
    });
  });
});

app/views/posts/index.html.erb
<%= content_for :page_title, t('page.title.index') %>

<%= render @posts %>

<% unless @posts.present? %>
  <section class="container is-larger mb-3">
    <div class="box">
      <h1 class="title">Não há nenhum post no momento</h1>
      <p>
        <%= link_to 'Criar post', new_post_path, data: {remote: true, type: :json}, class: 'button is-primary is-rounded new_post' if user_signed_in? %>
      </p>
    </div>
  </section>
<% end %>

app/views/posts/new.js.erb
$(document).ready(function(){
  $('#new_post').on('ajax:success', function(){
    $('#root_page').text('<%= t("page.title.new", model: @post.model_name) %>');
    $('.app').html("<%= j render 'new' %>");
    new FroalaEditor('#editor',{
      language: 'pt_pt'
    });
  });

  $('.new_post').on('ajax:success', function(){
    $('#root_page').text('<%= t("page.title.new", model: @post.model_name) %>');
    $('.app').html("<%= j render 'new' %>");
    new FroalaEditor('#editor',{
      language: 'pt_pt'
    });
  });
});

app/views/posts/show.js.erb
$(document).ready(function(){
  $('.show_post').on("ajax:success", function(){
    $('#messages').remove();
    $('#root_page').text('<%= t("page.title.show", model: @post.model_name) %>');
    $('.app').html("<%= j render 'show' %>");
    $('.delete_comment').text(I18n.t('page.links.delete', {model: "Comentário"}));
  });

   $('.show_post').on("ajax:error", function(e){
    console.log(e.detail);
   });
})

app/views/posts/update.js.erb
$(document).ready(function(){
  $("form[data-remote='true']").on('ajax:success', function(){
    $('.app').html("<%= j render 'show', post: @post %>");
    Toastify({
      text: I18n.t('messages.success.update',{model: "<%= @post.model_name %>"}),
      position: "center",
      gravity: "top",
      backgroundColor: "linear-gradient(to right, #00b09b, #96c93d)"
    }).showToast();
  });

  $("form[data-remote='true']").on('ajax:error', function(){
    Toastify({
      text: I18n.t('messages.error.update',{model: "<%= @post.model_name %>"}),
      position: "center",
      gravity: "top",
      backgroundColor: "linear-gradient(to right, #00b09b, #96c93d)"
    }).showToast();
  });
});

app/views/shared/_footer.html.erb
  <nav class="navbar hero is-small is-info is-bold" id="footer">
  <div class="hero-body">
    <div class="container">
      <span>Todos os direitos reservados. 2020 - Demo Blog</span>
    </div>
  </div>
</nav>

app/views/shared/_menu.html.erb
<nav class="navbar hero is-small is-info is-bold">
  <div class="hero-body">
    <div class="container">
      <div class="columns is-multiline is-mobile">
        <div class="column">
          <h1 class="title">
            <%= link_to yield(:page_title), root_path, remote: true, id: 'root_page' %>            
          </h1>
          <%= link_to t('menu.links.home'), root_path, id:'home_page', 
                                        class: "button is-link is-rounded mt-3 #{action_name == 'index' ? 'is-warning' : ''}",
                                        data: { remote: true} %>         
          <%= link_to t('menu.links.about'), about_path, data: {remote: true, type: :json}, 
                                          id: 'about_page', 
                                          class: "button is-link is-rounded mt-3 #{action_name == 'about' ? 'is-warning' : ''}" %>   
          <%= link_to t('menu.links.contact'), contact_path, data: {remote: true, type: :json},  
                                              id: 'contact_page', 
                                              class: "button is-link is-rounded mt-3 #{action_name == 'contact' ? 'is-warning' : ''}" %>               
          
          
        </div>
        
        <div class="column">
          <h1 class="is-pulled-right">
            <%= link_to t('menu.links.new_post'), new_post_path, data: {remote: true, type: :json}, id: 'new_post', class: 'button is-primary is-rounded' if user_signed_in? %>
            <%= link_to t('menu.links.login'), new_user_session_path, class: 'button is-primary is-rounded' unless user_signed_in? %>
            <%= link_to t('menu.links.logout'), destroy_user_session_path, method: :delete, class: 'button is-danger is-rounded' if user_signed_in? %>
          </h1>

          <% if user_signed_in? %>
            <h3 class="is-pulled-right mt-3 mr-3">
              <%= current_user.email %>
            </h3>
          <% end %>

        </div>
      </div>
    </div>
  </div>
</nav>